[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.45"
wasmtime = "0.30.0"
wasmtime-wasi = "0.30.0"
wai-bindgen-wasmtime = { path = "../../wai-bindgen/crates/wasmtime" }
